CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

0-hreadelf:
	$(CC) $(CFLAGS) 0-hreadelf.c -o 0-hreadelf

1-hreadelf:
	$(CC) $(CFLAGS) 1-hreadelf.c -o 1-hreadelf

2-hreadelf:
	$(CC) $(CFLAGS) 2-hreadelf.c -o 2-hreadelf

100-hreadelf:
	$(CC) $(CFLAGS) 100-hreadelf.c -o 100-hreadelf
